name: Build EPANET 2.2 and Create .deb Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust if needed for Linux Mint compatibility

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build dpkg-dev fakeroot git

      - name: Clone EPANET Source Code
        run: |
          git clone --recursive https://github.com/USEPA/EPANET2.2.git epanet
          cd epanet
          git submodule update --init --recursive

      - name: Create missing package_info.txt
        run: |
          cd epanet/SRC_engines/
          mkdir -p build
          echo "Package Maintainer: EPANET Team" > package_info.txt
          echo "Version: 2.2.0" >> package_info.txt
          echo "Description: EPANET 2.2 Water Network Analysis" >> package_info.txt
          mv package_info.txt build/package_info.txt
          cat build/package_info.txt

      - name: Configure and Build EPANET
        run: |
          cd epanet/SRC_engines/
          mkdir -p build && cd build
          cmake .. -G Ninja -DCPACK_PACKAGE_CONTACT="nirajpanwar24@gmail.com"
          ninja

      - name: Package as .deb
        run: |
          cd epanet/SRC_engines/build
          cpack -G DEB  # Creates a .deb package

      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: epanet-deb-package
          path: epanet/SRC_engines/build/*.deb
